# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_scaut.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(479, 196)
        Form.setMinimumSize(QtCore.QSize(479, 196))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_city = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_city.setObjectName("label_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.label_street = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_street.setObjectName("label_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.label_house = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_house.setObjectName("label_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.label_entrance = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_entrance.setObjectName("label_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entrance)
        self.lineEdit_entrance = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_entrance.setObjectName("lineEdit_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_entrance)
        self.comboBox_city = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.comboBox_street = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.comboBox_house = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_login = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_login.setObjectName("label_login")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login)
        self.label_pasw = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_pasw.setObjectName("label_pasw")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pasw)
        self.lineEdit_pasw = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_pasw.setObjectName("lineEdit_pasw")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pasw)
        self.label_host = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_host.setObjectName("label_host")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_host)
        self.lineEdit_host = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_host)
        self.label_port = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_port.setObjectName("label_port")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_port)
        self.horizontalLayout_3.addLayout(self.formLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_kpu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_kpu.setObjectName("pushButton_kpu")
        self.horizontalLayout.addWidget(self.pushButton_kpu)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_login.setText(_translate("Form", "Логин"))
        self.label_pasw.setText(_translate("Form", "Пароль"))
        self.label_host.setText(_translate("Form", "host"))
        self.label_port.setText(_translate("Form", "port"))
        self.pushButton_kpu.setText(_translate("Form", "КПУ"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
