# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_KPU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(489, 269)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_city = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_city.setObjectName("label_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.label_street = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_street.setObjectName("label_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.label_house = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_house.setObjectName("label_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.label_entrance = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_entrance.setObjectName("label_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entrance)
        self.label_floor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_floor.setObjectName("label_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_floor)
        self.comboBox_city = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.comboBox_street = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.comboBox_house = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.comboBox_entrance = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_entrance.setObjectName("comboBox_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_entrance)
        self.lineEdit_floor = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_floor.setObjectName("lineEdit_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_floor)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_serial = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_adress = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_adress.setObjectName("label_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adress)
        self.label_type = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_type.setObjectName("label_type")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.label_note = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_note.setObjectName("label_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_note)
        self.lineEdit_note = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_note.setObjectName("lineEdit_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_note)
        self.comboBox_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.spinBox_adress = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_adress.setSizeIncrement(QtCore.QSize(0, 0))
        self.spinBox_adress.setMinimum(1)
        self.spinBox_adress.setMaximum(255)
        self.spinBox_adress.setObjectName("spinBox_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_adress)
        self.horizontalLayout_3.addLayout(self.formLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_pu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_pu.setObjectName("pushButton_pu")
        self.horizontalLayout.addWidget(self.pushButton_pu)
        self.pushButton_replace = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout.addWidget(self.pushButton_replace)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_floor.setText(_translate("Form", "Этаж"))
        self.label_serial.setText(_translate("Form", "сер.ном"))
        self.label_adress.setText(_translate("Form", "Адрес"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.label_note.setText(_translate("Form", "Примечания"))
        self.comboBox_type.setItemText(0, _translate("Form", "ГВС"))
        self.comboBox_type.setItemText(1, _translate("Form", "ХВС"))
        self.comboBox_type.setItemText(2, _translate("Form", "Т"))
        self.comboBox_type.setItemText(3, _translate("Form", "Э"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.pushButton_pu.setText(_translate("Form", "ПУ"))
        self.pushButton_replace.setText(_translate("Form", "Замена"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
