# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_PU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 310)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_error = QtWidgets.QLabel(self.widget)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout_2.addWidget(self.label_error)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_serKpu = QtWidgets.QLabel(self.widget)
        self.label_serKpu.setObjectName("label_serKpu")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serKpu)
        self.lineEdit_serKpu = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_serKpu.setEnabled(True)
        self.lineEdit_serKpu.setObjectName("lineEdit_serKpu")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serKpu)
        self.label_city = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_city.sizePolicy().hasHeightForWidth())
        self.label_city.setSizePolicy(sizePolicy)
        self.label_city.setMinimumSize(QtCore.QSize(45, 20))
        self.label_city.setObjectName("label_city")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.comboBox_city = QtWidgets.QComboBox(self.widget)
        self.comboBox_city.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_city.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.label_street = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_street.sizePolicy().hasHeightForWidth())
        self.label_street.setSizePolicy(sizePolicy)
        self.label_street.setMinimumSize(QtCore.QSize(45, 20))
        self.label_street.setObjectName("label_street")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.comboBox_street = QtWidgets.QComboBox(self.widget)
        self.comboBox_street.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_street.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.label_house = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_house.sizePolicy().hasHeightForWidth())
        self.label_house.setSizePolicy(sizePolicy)
        self.label_house.setMinimumSize(QtCore.QSize(45, 20))
        self.label_house.setObjectName("label_house")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.comboBox_house = QtWidgets.QComboBox(self.widget)
        self.comboBox_house.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_house.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.label_flat = QtWidgets.QLabel(self.widget)
        self.label_flat.setObjectName("label_flat")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_flat)
        self.lineEdit_flat = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_flat.setEnabled(True)
        self.lineEdit_flat.setObjectName("lineEdit_flat")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_flat)
        self.label_type = QtWidgets.QLabel(self.widget)
        self.label_type.setObjectName("label_type")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(self.widget)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.setItemText(0, "")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.comboBox_entr = QtWidgets.QComboBox(self.widget)
        self.comboBox_entr.setObjectName("comboBox_entr")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_entr)
        self.label_entr = QtWidgets.QLabel(self.widget)
        self.label_entr.setObjectName("label_entr")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_entr)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setHorizontalSpacing(6)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_klemma = QtWidgets.QLabel(self.widget)
        self.label_klemma.setObjectName("label_klemma")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_klemma)
        self.lineEdit_klemma = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_klemma.setEnabled(True)
        self.lineEdit_klemma.setObjectName("lineEdit_klemma")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_klemma)
        self.label_serial = QtWidgets.QLabel(self.widget)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_serial.setEnabled(True)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_coef = QtWidgets.QLabel(self.widget)
        self.label_coef.setObjectName("label_coef")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_coef)
        self.lineEdit_coef = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_coef.setEnabled(True)
        self.lineEdit_coef.setObjectName("lineEdit_coef")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_coef)
        self.label_coefons = QtWidgets.QLabel(self.widget)
        self.label_coefons.setObjectName("label_coefons")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_coefons)
        self.lineEdit_coefons = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_coefons.setObjectName("lineEdit_coefons")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_coefons)
        self.label_marka = QtWidgets.QLabel(self.widget)
        self.label_marka.setObjectName("label_marka")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_marka)
        self.comboBox_marka = QtWidgets.QComboBox(self.widget)
        self.comboBox_marka.setObjectName("comboBox_marka")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_marka)
        self.dateEdit_dateInstall = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_dateInstall.setObjectName("dateEdit_dateInstall")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dateEdit_dateInstall)
        self.label_dateInstall = QtWidgets.QLabel(self.widget)
        self.label_dateInstall.setObjectName("label_dateInstall")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_dateInstall)
        self.verticalLayout_5.addLayout(self.formLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setEnabled(True)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.checkBox_type = QtWidgets.QCheckBox(self.widget)
        self.checkBox_type.setObjectName("checkBox_type")
        self.verticalLayout_6.addWidget(self.checkBox_type)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_13.addWidget(self.pushButton_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_stZn = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_stZn.sizePolicy().hasHeightForWidth())
        self.widget_stZn.setSizePolicy(sizePolicy)
        self.widget_stZn.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_stZn.setBaseSize(QtCore.QSize(0, 0))
        self.widget_stZn.setObjectName("widget_stZn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_stZn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_stZn = QtWidgets.QTableWidget(self.widget_stZn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_stZn.sizePolicy().hasHeightForWidth())
        self.tableWidget_stZn.setSizePolicy(sizePolicy)
        self.tableWidget_stZn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_stZn.setObjectName("tableWidget_stZn")
        self.tableWidget_stZn.setColumnCount(3)
        self.tableWidget_stZn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(2, item)
        self.tableWidget_stZn.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_stZn.horizontalHeader().setHighlightSections(True)
        self.tableWidget_stZn.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_stZn.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_stZn.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_stZn.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidget_stZn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_date = QtWidgets.QLabel(self.widget_stZn)
        self.label_date.setObjectName("label_date")
        self.verticalLayout.addWidget(self.label_date)
        self.dateTimeEdit_date = QtWidgets.QDateTimeEdit(self.widget_stZn)
        self.dateTimeEdit_date.setObjectName("dateTimeEdit_date")
        self.verticalLayout.addWidget(self.dateTimeEdit_date)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_pok = QtWidgets.QLabel(self.widget_stZn)
        self.label_pok.setObjectName("label_pok")
        self.verticalLayout_8.addWidget(self.label_pok)
        self.doubleSpinBox_val = QtWidgets.QDoubleSpinBox(self.widget_stZn)
        self.doubleSpinBox_val.setDecimals(4)
        self.doubleSpinBox_val.setMaximum(99999.9999)
        self.doubleSpinBox_val.setSingleStep(1.0)
        self.doubleSpinBox_val.setObjectName("doubleSpinBox_val")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_val)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_imp = QtWidgets.QLabel(self.widget_stZn)
        self.label_imp.setObjectName("label_imp")
        self.verticalLayout_9.addWidget(self.label_imp)
        self.spinBox_imp = QtWidgets.QSpinBox(self.widget_stZn)
        self.spinBox_imp.setMaximum(9999999)
        self.spinBox_imp.setObjectName("spinBox_imp")
        self.verticalLayout_9.addWidget(self.spinBox_imp)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.widget_stZn)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.pushButton_addStart = QtWidgets.QPushButton(self.widget_stZn)
        self.pushButton_addStart.setObjectName("pushButton_addStart")
        self.horizontalLayout_14.addWidget(self.pushButton_addStart)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addWidget(self.widget_stZn)
        self.widget_addFlat = QtWidgets.QWidget(Form)
        self.widget_addFlat.setObjectName("widget_addFlat")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_addFlat)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self.widget_addFlat)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_noteAdd = QtWidgets.QLineEdit(self.widget_addFlat)
        self.lineEdit_noteAdd.setObjectName("lineEdit_noteAdd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_noteAdd)
        self.label_noteAdd = QtWidgets.QLabel(self.widget_addFlat)
        self.label_noteAdd.setObjectName("label_noteAdd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_noteAdd)
        self.comboBox_entrAdd = QtWidgets.QComboBox(self.widget_addFlat)
        self.comboBox_entrAdd.setObjectName("comboBox_entrAdd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_entrAdd)
        self.label_entrAdd = QtWidgets.QLabel(self.widget_addFlat)
        self.label_entrAdd.setObjectName("label_entrAdd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_entrAdd)
        self.lineEdit_floorAdd = QtWidgets.QLineEdit(self.widget_addFlat)
        self.lineEdit_floorAdd.setObjectName("lineEdit_floorAdd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_floorAdd)
        self.label_floorAdd = QtWidgets.QLabel(self.widget_addFlat)
        self.label_floorAdd.setObjectName("label_floorAdd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_floorAdd)
        self.verticalLayout_3.addLayout(self.formLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_cansel = QtWidgets.QPushButton(self.widget_addFlat)
        self.pushButton_cansel.setObjectName("pushButton_cansel")
        self.horizontalLayout_2.addWidget(self.pushButton_cansel)
        self.pushButton_addFlat = QtWidgets.QPushButton(self.widget_addFlat)
        self.pushButton_addFlat.setObjectName("pushButton_addFlat")
        self.horizontalLayout_2.addWidget(self.pushButton_addFlat)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.widget_addFlat)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_serKpu.setText(_translate("Form", "S/N КПУ"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_flat.setText(_translate("Form", "Квартира"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.comboBox_type.setItemText(1, _translate("Form", "ГВС"))
        self.comboBox_type.setItemText(2, _translate("Form", "ХВС"))
        self.comboBox_type.setItemText(3, _translate("Form", "Т"))
        self.comboBox_type.setItemText(4, _translate("Form", "Э"))
        self.label_entr.setText(_translate("Form", "Подъезд"))
        self.label_klemma.setText(_translate("Form", "Клемма"))
        self.label_serial.setText(_translate("Form", "Сер.Ном ПУ"))
        self.label_coef.setText(_translate("Form", "Коэффициент"))
        self.label_coefons.setText(_translate("Form", "Коэф.общедомовой"))
        self.label_marka.setText(_translate("Form", "Марка"))
        self.label_dateInstall.setText(_translate("Form", "Дата установки"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.checkBox_type.setText(_translate("Form", "Домовой счетчик"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        item = self.tableWidget_stZn.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Дата"))
        item = self.tableWidget_stZn.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Показания"))
        item = self.tableWidget_stZn.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Импульсы"))
        self.label_date.setText(_translate("Form", "Дата"))
        self.label_pok.setText(_translate("Form", "Показания"))
        self.label_imp.setText(_translate("Form", "Импульсы"))
        self.pushButton_addStart.setText(_translate("Form", "Добавить"))
        self.label_2.setText(_translate("Form", "N квартиры нету в базе данных, хотите добавить?"))
        self.label_noteAdd.setText(_translate("Form", "Комментарий"))
        self.label_entrAdd.setText(_translate("Form", "Подъезд"))
        self.label_floorAdd.setText(_translate("Form", "Этаж"))
        self.pushButton_cansel.setText(_translate("Form", "Назад"))
        self.pushButton_addFlat.setText(_translate("Form", "Добавить"))
