# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_scaut.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(479, 196)
        Form.setMinimumSize(QtCore.QSize(479, 196))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_error = QtWidgets.QLabel(Form)
        self.label_error.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_error.setPalette(palette)
        self.label_error.setAcceptDrops(False)
        self.label_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_error.setText("")
        self.label_error.setTextFormat(QtCore.Qt.AutoText)
        self.label_error.setScaledContents(False)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setWordWrap(False)
        self.label_error.setIndent(-2)
        self.label_error.setOpenExternalLinks(False)
        self.label_error.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_city = QtWidgets.QLabel(Form)
        self.label_city.setObjectName("label_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.label_street = QtWidgets.QLabel(Form)
        self.label_street.setObjectName("label_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.label_house = QtWidgets.QLabel(Form)
        self.label_house.setObjectName("label_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.label_entr = QtWidgets.QLabel(Form)
        self.label_entr.setObjectName("label_entr")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entr)
        self.comboBox_city = QtWidgets.QComboBox(Form)
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.comboBox_street = QtWidgets.QComboBox(Form)
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.comboBox_house = QtWidgets.QComboBox(Form)
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.spinBox_entr = QtWidgets.QSpinBox(Form)
        self.spinBox_entr.setMinimum(1)
        self.spinBox_entr.setObjectName("spinBox_entr")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_entr)
        self.label_host = QtWidgets.QLabel(Form)
        self.label_host.setObjectName("label_host")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_host)
        self.lineEdit_host = QtWidgets.QLineEdit(Form)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_host)
        self.label_port = QtWidgets.QLabel(Form)
        self.label_port.setObjectName("label_port")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(Form)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_port)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_login = QtWidgets.QLabel(Form)
        self.label_login.setObjectName("label_login")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(Form)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login)
        self.label_pasw = QtWidgets.QLabel(Form)
        self.label_pasw.setObjectName("label_pasw")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pasw)
        self.lineEdit_pasw = QtWidgets.QLineEdit(Form)
        self.lineEdit_pasw.setObjectName("lineEdit_pasw")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pasw)
        self.label_fdbLogin = QtWidgets.QLabel(Form)
        self.label_fdbLogin.setObjectName("label_fdbLogin")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_fdbLogin)
        self.lineEdit_fdbLogin = QtWidgets.QLineEdit(Form)
        self.lineEdit_fdbLogin.setObjectName("lineEdit_fdbLogin")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fdbLogin)
        self.label_fdbPasw = QtWidgets.QLabel(Form)
        self.label_fdbPasw.setObjectName("label_fdbPasw")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_fdbPasw)
        self.lineEdit_fdbPasw = QtWidgets.QLineEdit(Form)
        self.lineEdit_fdbPasw.setObjectName("lineEdit_fdbPasw")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fdbPasw)
        self.label_fdbName = QtWidgets.QLabel(Form)
        self.label_fdbName.setObjectName("label_fdbName")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_fdbName)
        self.lineEdit_fdbName = QtWidgets.QLineEdit(Form)
        self.lineEdit_fdbName.setObjectName("lineEdit_fdbName")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fdbName)
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setObjectName("label_name")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.horizontalLayout_3.addLayout(self.formLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_kpu = QtWidgets.QPushButton(Form)
        self.pushButton_kpu.setObjectName("pushButton_kpu")
        self.horizontalLayout.addWidget(self.pushButton_kpu)
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entr.setText(_translate("Form", "Подъезд"))
        self.label_host.setText(_translate("Form", "ip rassbery"))
        self.label_port.setText(_translate("Form", "port rassbery"))
        self.lineEdit_port.setText(_translate("Form", "23"))
        self.label_login.setText(_translate("Form", "login user"))
        self.lineEdit_login.setText(_translate("Form", "pi"))
        self.label_pasw.setText(_translate("Form", "password user"))
        self.lineEdit_pasw.setText(_translate("Form", "alpha1"))
        self.label_fdbLogin.setText(_translate("Form", "fdb login"))
        self.lineEdit_fdbLogin.setText(_translate("Form", "SYSDBA"))
        self.label_fdbPasw.setText(_translate("Form", "fdb password"))
        self.lineEdit_fdbPasw.setText(_translate("Form", "masterkey"))
        self.label_fdbName.setText(_translate("Form", "fdn name"))
        self.lineEdit_fdbName.setText(_translate("Form", "counters"))
        self.label_name.setText(_translate("Form", "version_fdb"))
        self.pushButton_kpu.setText(_translate("Form", "КПУ"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
