# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_KPU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(899, 301)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_kpu = QtWidgets.QTabWidget(Form)
        self.tabWidget_kpu.setObjectName("tabWidget_kpu")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_error = QtWidgets.QLabel(self.tab)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_city = QtWidgets.QLabel(self.tab)
        self.label_city.setObjectName("label_city")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.label_street = QtWidgets.QLabel(self.tab)
        self.label_street.setObjectName("label_street")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.label_house = QtWidgets.QLabel(self.tab)
        self.label_house.setObjectName("label_house")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.label_entrance = QtWidgets.QLabel(self.tab)
        self.label_entrance.setObjectName("label_entrance")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entrance)
        self.label_floor = QtWidgets.QLabel(self.tab)
        self.label_floor.setObjectName("label_floor")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_floor)
        self.lineEdit_floor = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_floor.setEnabled(True)
        self.lineEdit_floor.setObjectName("lineEdit_floor")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_floor)
        self.comboBox_city = QtWidgets.QComboBox(self.tab)
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.comboBox_street = QtWidgets.QComboBox(self.tab)
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.comboBox_house = QtWidgets.QComboBox(self.tab)
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.comboBox_entrance = QtWidgets.QComboBox(self.tab)
        self.comboBox_entrance.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_entrance.setObjectName("comboBox_entrance")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_entrance)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_serial = QtWidgets.QLabel(self.tab)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_serial.setEnabled(True)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_adress = QtWidgets.QLabel(self.tab)
        self.label_adress.setObjectName("label_adress")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adress)
        self.spinBox_adress = QtWidgets.QSpinBox(self.tab)
        self.spinBox_adress.setSizeIncrement(QtCore.QSize(0, 0))
        self.spinBox_adress.setMinimum(1)
        self.spinBox_adress.setMaximum(255)
        self.spinBox_adress.setProperty("value", 255)
        self.spinBox_adress.setObjectName("spinBox_adress")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_adress)
        self.label_type = QtWidgets.QLabel(self.tab)
        self.label_type.setObjectName("label_type")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(self.tab)
        self.comboBox_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_type.setObjectName("comboBox_type")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.label_note = QtWidgets.QLabel(self.tab)
        self.label_note.setObjectName("label_note")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_note)
        self.textEdit_note = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_note.sizePolicy().hasHeightForWidth())
        self.textEdit_note.setSizePolicy(sizePolicy)
        self.textEdit_note.setMinimumSize(QtCore.QSize(0, 20))
        self.textEdit_note.setObjectName("textEdit_note")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit_note)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.formLayout_3.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setEnabled(True)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton_pu = QtWidgets.QPushButton(self.tab)
        self.pushButton_pu.setObjectName("pushButton_pu")
        self.horizontalLayout_8.addWidget(self.pushButton_pu)
        self.pushButton_replace = QtWidgets.QPushButton(self.tab)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout_8.addWidget(self.pushButton_replace)
        self.pushButton_save = QtWidgets.QPushButton(self.tab)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_8.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.tabWidget_kpu.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_history = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(9)
        self.tableWidget_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.tableWidget_history)
        self.tabWidget_kpu.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_kpu)
        self.widget_kpuNew = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_kpuNew.sizePolicy().hasHeightForWidth())
        self.widget_kpuNew.setSizePolicy(sizePolicy)
        self.widget_kpuNew.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_kpuNew.setBaseSize(QtCore.QSize(0, 0))
        self.widget_kpuNew.setObjectName("widget_kpuNew")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_kpuNew)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_10.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.label_serialNew = QtWidgets.QLabel(self.widget_kpuNew)
        self.label_serialNew.setObjectName("label_serialNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_serialNew)
        self.lineEdit_serialNew = QtWidgets.QLineEdit(self.widget_kpuNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_serialNew.sizePolicy().hasHeightForWidth())
        self.lineEdit_serialNew.setSizePolicy(sizePolicy)
        self.lineEdit_serialNew.setObjectName("lineEdit_serialNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serialNew)
        self.label_typeNew = QtWidgets.QLabel(self.widget_kpuNew)
        self.label_typeNew.setObjectName("label_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_typeNew)
        self.comboBox_typeNew = QtWidgets.QComboBox(self.widget_kpuNew)
        self.comboBox_typeNew.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_typeNew.setObjectName("comboBox_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_typeNew)
        self.horizontalLayout_5.addLayout(self.formLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.checkBoxNew = QtWidgets.QCheckBox(self.widget_kpuNew)
        self.checkBoxNew.setEnabled(True)
        self.checkBoxNew.setCheckable(True)
        self.checkBoxNew.setChecked(True)
        self.checkBoxNew.setObjectName("checkBoxNew")
        self.verticalLayout_4.addWidget(self.checkBoxNew)
        self.checkBox_st_zn = QtWidgets.QCheckBox(self.widget_kpuNew)
        self.checkBox_st_zn.setCheckable(True)
        self.checkBox_st_zn.setChecked(False)
        self.checkBox_st_zn.setObjectName("checkBox_st_zn")
        self.verticalLayout_4.addWidget(self.checkBox_st_zn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_noteNew = QtWidgets.QLabel(self.widget_kpuNew)
        self.label_noteNew.setObjectName("label_noteNew")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_noteNew)
        self.lineEdit_noteNew = QtWidgets.QLineEdit(self.widget_kpuNew)
        self.lineEdit_noteNew.setObjectName("lineEdit_noteNew")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_noteNew)
        self.verticalLayout_3.addLayout(self.formLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget_kpuNew)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 4, 7), QtCore.QTime(15, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2020, 4, 7))
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setCalendarPopup(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_11.addWidget(self.dateTimeEdit)
        self.pushButton_selectDate = QtWidgets.QPushButton(self.widget_kpuNew)
        self.pushButton_selectDate.setObjectName("pushButton_selectDate")
        self.horizontalLayout_11.addWidget(self.pushButton_selectDate)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.widget_st_zn = QtWidgets.QWidget(self.widget_kpuNew)
        self.widget_st_zn.setObjectName("widget_st_zn")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_st_zn)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_1 = QtWidgets.QFormLayout()
        self.formLayout_1.setObjectName("formLayout_1")
        self.label_k1 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k1.setObjectName("label_k1")
        self.formLayout_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_k1)
        self.lineEdit_k1 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k1.sizePolicy().hasHeightForWidth())
        self.lineEdit_k1.setSizePolicy(sizePolicy)
        self.lineEdit_k1.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k1.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_k1.setText("")
        self.lineEdit_k1.setFrame(True)
        self.lineEdit_k1.setCursorPosition(0)
        self.lineEdit_k1.setObjectName("lineEdit_k1")
        self.formLayout_1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k1)
        self.label_k2 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k2.setObjectName("label_k2")
        self.formLayout_1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_k2)
        self.lineEdit_k2 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k2.sizePolicy().hasHeightForWidth())
        self.lineEdit_k2.setSizePolicy(sizePolicy)
        self.lineEdit_k2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k2.setText("")
        self.lineEdit_k2.setObjectName("lineEdit_k2")
        self.formLayout_1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k2)
        self.label_k3 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k3.setObjectName("label_k3")
        self.formLayout_1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_k3)
        self.lineEdit_k3 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k3.sizePolicy().hasHeightForWidth())
        self.lineEdit_k3.setSizePolicy(sizePolicy)
        self.lineEdit_k3.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k3.setObjectName("lineEdit_k3")
        self.formLayout_1.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k3)
        self.label_k4 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k4.setObjectName("label_k4")
        self.formLayout_1.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_k4)
        self.lineEdit_k4 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k4.sizePolicy().hasHeightForWidth())
        self.lineEdit_k4.setSizePolicy(sizePolicy)
        self.lineEdit_k4.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k4.setObjectName("lineEdit_k4")
        self.formLayout_1.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k4)
        self.horizontalLayout.addLayout(self.formLayout_1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_k5 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k5.setObjectName("label_k5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_k5)
        self.label_k6 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k6.setObjectName("label_k6")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_k6)
        self.label_k7 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k7.setObjectName("label_k7")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_k7)
        self.label_k8 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k8.setObjectName("label_k8")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_k8)
        self.lineEdit_k5 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k5.sizePolicy().hasHeightForWidth())
        self.lineEdit_k5.setSizePolicy(sizePolicy)
        self.lineEdit_k5.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k5.setObjectName("lineEdit_k5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k5)
        self.lineEdit_k6 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k6.sizePolicy().hasHeightForWidth())
        self.lineEdit_k6.setSizePolicy(sizePolicy)
        self.lineEdit_k6.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k6.setObjectName("lineEdit_k6")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k6)
        self.lineEdit_k7 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k7.sizePolicy().hasHeightForWidth())
        self.lineEdit_k7.setSizePolicy(sizePolicy)
        self.lineEdit_k7.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k7.setObjectName("lineEdit_k7")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k7)
        self.lineEdit_k8 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k8.sizePolicy().hasHeightForWidth())
        self.lineEdit_k8.setSizePolicy(sizePolicy)
        self.lineEdit_k8.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k8.setObjectName("lineEdit_k8")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k8)
        self.horizontalLayout.addLayout(self.formLayout_5)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_k9 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k9.setObjectName("label_k9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_k9)
        self.lineEdit_k9 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k9.sizePolicy().hasHeightForWidth())
        self.lineEdit_k9.setSizePolicy(sizePolicy)
        self.lineEdit_k9.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k9.setText("")
        self.lineEdit_k9.setObjectName("lineEdit_k9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k9)
        self.label_k10 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k10.setObjectName("label_k10")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_k10)
        self.lineEdit_k10 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k10.sizePolicy().hasHeightForWidth())
        self.lineEdit_k10.setSizePolicy(sizePolicy)
        self.lineEdit_k10.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k10.setObjectName("lineEdit_k10")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k10)
        self.label_k11 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k11.setObjectName("label_k11")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_k11)
        self.lineEdit_k11 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k11.sizePolicy().hasHeightForWidth())
        self.lineEdit_k11.setSizePolicy(sizePolicy)
        self.lineEdit_k11.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k11.setObjectName("lineEdit_k11")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k11)
        self.label_k12 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k12.setObjectName("label_k12")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_k12)
        self.lineEdit_k12 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k12.sizePolicy().hasHeightForWidth())
        self.lineEdit_k12.setSizePolicy(sizePolicy)
        self.lineEdit_k12.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k12.setObjectName("lineEdit_k12")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k12)
        self.horizontalLayout.addLayout(self.formLayout_9)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_k13 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k13.setObjectName("label_k13")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_k13)
        self.lineEdit_k13 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k13.sizePolicy().hasHeightForWidth())
        self.lineEdit_k13.setSizePolicy(sizePolicy)
        self.lineEdit_k13.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k13.setText("")
        self.lineEdit_k13.setObjectName("lineEdit_k13")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k13)
        self.label_k14 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k14.setObjectName("label_k14")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_k14)
        self.lineEdit_k14 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k14.sizePolicy().hasHeightForWidth())
        self.lineEdit_k14.setSizePolicy(sizePolicy)
        self.lineEdit_k14.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k14.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k14.setObjectName("lineEdit_k14")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k14)
        self.label_k15 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k15.setObjectName("label_k15")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_k15)
        self.lineEdit_k15 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k15.sizePolicy().hasHeightForWidth())
        self.lineEdit_k15.setSizePolicy(sizePolicy)
        self.lineEdit_k15.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k15.setObjectName("lineEdit_k15")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k15)
        self.label_k16 = QtWidgets.QLabel(self.widget_st_zn)
        self.label_k16.setObjectName("label_k16")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_k16)
        self.lineEdit_k16 = QtWidgets.QLineEdit(self.widget_st_zn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k16.sizePolicy().hasHeightForWidth())
        self.lineEdit_k16.setSizePolicy(sizePolicy)
        self.lineEdit_k16.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_k16.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_k16.setObjectName("lineEdit_k16")
        self.formLayout_13.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_k16)
        self.horizontalLayout.addLayout(self.formLayout_13)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_st_zn)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.label_errorNew = QtWidgets.QLabel(self.widget_kpuNew)
        self.label_errorNew.setText("")
        self.label_errorNew.setObjectName("label_errorNew")
        self.horizontalLayout_6.addWidget(self.label_errorNew)
        self.pushButton_replaceNew = QtWidgets.QPushButton(self.widget_kpuNew)
        self.pushButton_replaceNew.setObjectName("pushButton_replaceNew")
        self.horizontalLayout_6.addWidget(self.pushButton_replaceNew)
        self.pushButton_canselNew = QtWidgets.QPushButton(self.widget_kpuNew)
        self.pushButton_canselNew.setObjectName("pushButton_canselNew")
        self.horizontalLayout_6.addWidget(self.pushButton_canselNew)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addWidget(self.widget_kpuNew)

        self.retranslateUi(Form)
        self.tabWidget_kpu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_floor.setText(_translate("Form", "Этаж"))
        self.label_serial.setText(_translate("Form", "сер.ном"))
        self.label_adress.setText(_translate("Form", "Адрес"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.label_note.setText(_translate("Form", "Примечания"))
        self.textEdit_note.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.pushButton_pu.setText(_translate("Form", "ПУ"))
        self.pushButton_replace.setText(_translate("Form", "Замена"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.tabWidget_kpu.setTabText(self.tabWidget_kpu.indexOf(self.tab), _translate("Form", "Информация о КПУ"))
        item = self.tableWidget_history.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Город"))
        item = self.tableWidget_history.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Улица"))
        item = self.tableWidget_history.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Дом"))
        item = self.tableWidget_history.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Подъезд"))
        item = self.tableWidget_history.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Этаж"))
        item = self.tableWidget_history.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Адрес"))
        item = self.tableWidget_history.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Работоспособность"))
        item = self.tableWidget_history.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Дата редактирования"))
        item = self.tableWidget_history.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Примечания"))
        self.tabWidget_kpu.setTabText(self.tabWidget_kpu.indexOf(self.tab_2), _translate("Form", "История замены"))
        self.label_serialNew.setText(_translate("Form", "сер.ном"))
        self.label_typeNew.setText(_translate("Form", "Тип"))
        self.checkBoxNew.setText(_translate("Form", "работоспособность"))
        self.checkBox_st_zn.setText(_translate("Form", "с заменой стартовых значений"))
        self.label_noteNew.setText(_translate("Form", "Примечания"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "dd.MM.yyyy H:mm"))
        self.pushButton_selectDate.setText(_translate("Form", "Обновить"))
        self.label_k1.setText(_translate("Form", "1 клемма"))
        self.label_k2.setText(_translate("Form", "2 клемма"))
        self.label_k3.setText(_translate("Form", "3 клемма"))
        self.label_k4.setText(_translate("Form", "4 клемма"))
        self.label_k5.setText(_translate("Form", "5 клемма"))
        self.label_k6.setText(_translate("Form", "6 клемма"))
        self.label_k7.setText(_translate("Form", "7 клемма"))
        self.label_k8.setText(_translate("Form", "8 клемма"))
        self.label_k9.setText(_translate("Form", "9 клемма"))
        self.label_k10.setText(_translate("Form", "10 клемма"))
        self.label_k11.setText(_translate("Form", "11 клемма"))
        self.label_k12.setText(_translate("Form", "12 клемма"))
        self.label_k13.setText(_translate("Form", "13 клемма"))
        self.label_k14.setText(_translate("Form", "14 клемма"))
        self.label_k15.setText(_translate("Form", "15 клемма"))
        self.label_k16.setText(_translate("Form", "16 клемма"))
        self.pushButton_replaceNew.setText(_translate("Form", "Заменить"))
        self.pushButton_canselNew.setText(_translate("Form", "Отмена"))
