pyuic5 menu.ui -o menu_ui.py
pyuic5 scaut.ui -o scaut_ui.py
pyuic5 add_scaut.ui -o add_scaut_ui.py
pyuic5 KPU.ui -o KPU_ui.py
pyuic5 add_KPU.ui -o add_KPU_ui.py
pyuic5 PU.ui -o PU_ui.py
pyuic5 add_PU.ui -o add_PU_ui.py
pyuic5 info_PU.ui -o info_PU_ui.py
pyuic5 connected_BD.ui -o connected_BD_ui.py