# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_PU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 310)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_error = QtWidgets.QLabel(self.tab_info)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout_5.addWidget(self.label_error)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_serKpu = QtWidgets.QLabel(self.tab_info)
        self.label_serKpu.setObjectName("label_serKpu")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serKpu)
        self.lineEdit_serKpu = QtWidgets.QLineEdit(self.tab_info)
        self.lineEdit_serKpu.setEnabled(True)
        self.lineEdit_serKpu.setObjectName("lineEdit_serKpu")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serKpu)
        self.label_city = QtWidgets.QLabel(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_city.sizePolicy().hasHeightForWidth())
        self.label_city.setSizePolicy(sizePolicy)
        self.label_city.setMinimumSize(QtCore.QSize(45, 20))
        self.label_city.setObjectName("label_city")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.comboBox_city = QtWidgets.QComboBox(self.tab_info)
        self.comboBox_city.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_city.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.label_street = QtWidgets.QLabel(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_street.sizePolicy().hasHeightForWidth())
        self.label_street.setSizePolicy(sizePolicy)
        self.label_street.setMinimumSize(QtCore.QSize(45, 20))
        self.label_street.setObjectName("label_street")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.comboBox_street = QtWidgets.QComboBox(self.tab_info)
        self.comboBox_street.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_street.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.label_house = QtWidgets.QLabel(self.tab_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_house.sizePolicy().hasHeightForWidth())
        self.label_house.setSizePolicy(sizePolicy)
        self.label_house.setMinimumSize(QtCore.QSize(45, 20))
        self.label_house.setObjectName("label_house")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.comboBox_house = QtWidgets.QComboBox(self.tab_info)
        self.comboBox_house.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox_house.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.label_flat = QtWidgets.QLabel(self.tab_info)
        self.label_flat.setObjectName("label_flat")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_flat)
        self.lineEdit_flat = QtWidgets.QLineEdit(self.tab_info)
        self.lineEdit_flat.setEnabled(True)
        self.lineEdit_flat.setObjectName("lineEdit_flat")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_flat)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setHorizontalSpacing(6)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_klemma = QtWidgets.QLabel(self.tab_info)
        self.label_klemma.setObjectName("label_klemma")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_klemma)
        self.lineEdit_klemma = QtWidgets.QLineEdit(self.tab_info)
        self.lineEdit_klemma.setEnabled(True)
        self.lineEdit_klemma.setObjectName("lineEdit_klemma")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_klemma)
        self.label_serial = QtWidgets.QLabel(self.tab_info)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.tab_info)
        self.lineEdit_serial.setEnabled(True)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_type = QtWidgets.QLabel(self.tab_info)
        self.label_type.setObjectName("label_type")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.lineEdit_coef = QtWidgets.QLineEdit(self.tab_info)
        self.lineEdit_coef.setEnabled(True)
        self.lineEdit_coef.setObjectName("lineEdit_coef")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_coef)
        self.label_coef = QtWidgets.QLabel(self.tab_info)
        self.label_coef.setObjectName("label_coef")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_coef)
        self.comboBox_marka = QtWidgets.QComboBox(self.tab_info)
        self.comboBox_marka.setObjectName("comboBox_marka")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_marka)
        self.label_marka = QtWidgets.QLabel(self.tab_info)
        self.label_marka.setObjectName("label_marka")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_marka)
        self.comboBox_type = QtWidgets.QComboBox(self.tab_info)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.setItemText(0, "")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.horizontalLayout_4.addLayout(self.formLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.tab_info)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setObjectName("label_4")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_floor = QtWidgets.QLabel(self.frame)
        self.label_floor.setMinimumSize(QtCore.QSize(0, 20))
        self.label_floor.setAutoFillBackground(False)
        self.label_floor.setObjectName("label_floor")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_floor)
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setMinimumSize(QtCore.QSize(0, 20))
        self.label_35.setObjectName("label_35")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_pokaz = QtWidgets.QLabel(self.frame)
        self.label_pokaz.setMinimumSize(QtCore.QSize(0, 20))
        self.label_pokaz.setAutoFillBackground(False)
        self.label_pokaz.setObjectName("label_pokaz")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_pokaz)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setMinimumSize(QtCore.QSize(0, 20))
        self.label_17.setObjectName("label_17")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_dateLast = QtWidgets.QLabel(self.frame)
        self.label_dateLast.setMinimumSize(QtCore.QSize(0, 20))
        self.label_dateLast.setAutoFillBackground(False)
        self.label_dateLast.setObjectName("label_dateLast")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_dateLast)
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setMinimumSize(QtCore.QSize(0, 20))
        self.label_37.setObjectName("label_37")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_dateOn = QtWidgets.QLabel(self.frame)
        self.label_dateOn.setMinimumSize(QtCore.QSize(0, 20))
        self.label_dateOn.setAutoFillBackground(False)
        self.label_dateOn.setObjectName("label_dateOn")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_dateOn)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setObjectName("label_9")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_dateOff = QtWidgets.QLabel(self.frame)
        self.label_dateOff.setMinimumSize(QtCore.QSize(0, 20))
        self.label_dateOff.setAutoFillBackground(False)
        self.label_dateOff.setObjectName("label_dateOff")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_dateOff)
        self.label_entr = QtWidgets.QLabel(self.frame)
        self.label_entr.setMinimumSize(QtCore.QSize(0, 20))
        self.label_entr.setAutoFillBackground(False)
        self.label_entr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_entr.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_entr.setObjectName("label_entr")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_entr)
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setMinimumSize(QtCore.QSize(0, 20))
        self.label_1.setObjectName("label_1")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_11)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.checkBox = QtWidgets.QCheckBox(self.tab_info)
        self.checkBox.setEnabled(True)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.tab_info)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.pushButton_kpu = QtWidgets.QPushButton(self.tab_info)
        self.pushButton_kpu.setObjectName("pushButton_kpu")
        self.horizontalLayout_13.addWidget(self.pushButton_kpu)
        self.pushButton_replace = QtWidgets.QPushButton(self.tab_info)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout_13.addWidget(self.pushButton_replace)
        self.pushButton_save = QtWidgets.QPushButton(self.tab_info)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_13.addWidget(self.pushButton_save)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab_info, "")
        self.tab_startZn = QtWidgets.QWidget()
        self.tab_startZn.setObjectName("tab_startZn")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_startZn)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_stZn = QtWidgets.QTableWidget(self.tab_startZn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_stZn.sizePolicy().hasHeightForWidth())
        self.tableWidget_stZn.setSizePolicy(sizePolicy)
        self.tableWidget_stZn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_stZn.setObjectName("tableWidget_stZn")
        self.tableWidget_stZn.setColumnCount(3)
        self.tableWidget_stZn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stZn.setHorizontalHeaderItem(2, item)
        self.tableWidget_stZn.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_stZn.horizontalHeader().setHighlightSections(True)
        self.tableWidget_stZn.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_stZn.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_stZn.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_stZn.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.tableWidget_stZn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_date = QtWidgets.QLabel(self.tab_startZn)
        self.label_date.setObjectName("label_date")
        self.verticalLayout.addWidget(self.label_date)
        self.dateTimeEdit_date = QtWidgets.QDateTimeEdit(self.tab_startZn)
        self.dateTimeEdit_date.setObjectName("dateTimeEdit_date")
        self.verticalLayout.addWidget(self.dateTimeEdit_date)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_pok = QtWidgets.QLabel(self.tab_startZn)
        self.label_pok.setObjectName("label_pok")
        self.verticalLayout_8.addWidget(self.label_pok)
        self.lineEdit_pok = QtWidgets.QLineEdit(self.tab_startZn)
        self.lineEdit_pok.setObjectName("lineEdit_pok")
        self.verticalLayout_8.addWidget(self.lineEdit_pok)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_imp = QtWidgets.QLabel(self.tab_startZn)
        self.label_imp.setObjectName("label_imp")
        self.verticalLayout_9.addWidget(self.label_imp)
        self.lineEdit_imp = QtWidgets.QLineEdit(self.tab_startZn)
        self.lineEdit_imp.setObjectName("lineEdit_imp")
        self.verticalLayout_9.addWidget(self.lineEdit_imp)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.pushButton_addStart = QtWidgets.QPushButton(self.tab_startZn)
        self.pushButton_addStart.setObjectName("pushButton_addStart")
        self.horizontalLayout_14.addWidget(self.pushButton_addStart)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_startZn, "")
        self.tab_value = QtWidgets.QWidget()
        self.tab_value.setObjectName("tab_value")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_value)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.tab_value)
        self.dateTimeEdit_start.setDate(QtCore.QDate(2020, 2, 13))
        self.dateTimeEdit_start.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.dateTimeEdit_start.setCalendarPopup(True)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_start)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.tab_value)
        self.dateTimeEdit_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 19), QtCore.QTime(9, 0, 0)))
        self.dateTimeEdit_end.setDate(QtCore.QDate(2020, 2, 19))
        self.dateTimeEdit_end.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.dateTimeEdit_end.setCalendarPopup(True)
        self.dateTimeEdit_end.setCurrentSectionIndex(0)
        self.dateTimeEdit_end.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_end)
        self.pushButton_showVal = QtWidgets.QPushButton(self.tab_value)
        self.pushButton_showVal.setObjectName("pushButton_showVal")
        self.horizontalLayout_8.addWidget(self.pushButton_showVal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tableWidget_dateVal = QtWidgets.QTableWidget(self.tab_value)
        self.tableWidget_dateVal.setObjectName("tableWidget_dateVal")
        self.tableWidget_dateVal.setColumnCount(0)
        self.tableWidget_dateVal.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_dateVal)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_value, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_history)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_history = QtWidgets.QTableWidget(self.tab_history)
        self.tableWidget_history.setObjectName("tableWidget_history")
        self.tableWidget_history.setColumnCount(9)
        self.tableWidget_history.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_history.setHorizontalHeaderItem(8, item)
        self.verticalLayout_7.addWidget(self.tableWidget_history)
        self.tabWidget.addTab(self.tab_history, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.widget_puNew = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_puNew.sizePolicy().hasHeightForWidth())
        self.widget_puNew.setSizePolicy(sizePolicy)
        self.widget_puNew.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_puNew.setBaseSize(QtCore.QSize(0, 0))
        self.widget_puNew.setObjectName("widget_puNew")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_puNew)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_serialNew = QtWidgets.QLabel(self.widget_puNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_serialNew.sizePolicy().hasHeightForWidth())
        self.label_serialNew.setSizePolicy(sizePolicy)
        self.label_serialNew.setMinimumSize(QtCore.QSize(70, 20))
        self.label_serialNew.setMaximumSize(QtCore.QSize(61, 20))
        self.label_serialNew.setObjectName("label_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serialNew)
        self.lineEdit_serialNew = QtWidgets.QLineEdit(self.widget_puNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_serialNew.sizePolicy().hasHeightForWidth())
        self.lineEdit_serialNew.setSizePolicy(sizePolicy)
        self.lineEdit_serialNew.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEdit_serialNew.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lineEdit_serialNew.setObjectName("lineEdit_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serialNew)
        self.label_coefNew = QtWidgets.QLabel(self.widget_puNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_coefNew.sizePolicy().hasHeightForWidth())
        self.label_coefNew.setSizePolicy(sizePolicy)
        self.label_coefNew.setMinimumSize(QtCore.QSize(70, 20))
        self.label_coefNew.setMaximumSize(QtCore.QSize(61, 20))
        self.label_coefNew.setObjectName("label_coefNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_coefNew)
        self.lineEdit_coefNew = QtWidgets.QLineEdit(self.widget_puNew)
        self.lineEdit_coefNew.setMinimumSize(QtCore.QSize(90, 20))
        self.lineEdit_coefNew.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lineEdit_coefNew.setObjectName("lineEdit_coefNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_coefNew)
        self.horizontalLayout_10.addLayout(self.formLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_markaNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_markaNew.setObjectName("label_markaNew")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_markaNew)
        self.comboBox_markaNew = QtWidgets.QComboBox(self.widget_puNew)
        self.comboBox_markaNew.setObjectName("comboBox_markaNew")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_markaNew)
        self.label_klemmaNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_klemmaNew.setObjectName("label_klemmaNew")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_klemmaNew)
        self.comboBox_klemmaNew = QtWidgets.QComboBox(self.widget_puNew)
        self.comboBox_klemmaNew.setObjectName("comboBox_klemmaNew")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_klemmaNew)
        self.horizontalLayout_10.addLayout(self.formLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_noteNew = QtWidgets.QLabel(self.widget_puNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_noteNew.sizePolicy().hasHeightForWidth())
        self.label_noteNew.setSizePolicy(sizePolicy)
        self.label_noteNew.setMinimumSize(QtCore.QSize(70, 20))
        self.label_noteNew.setMaximumSize(QtCore.QSize(61, 20))
        self.label_noteNew.setObjectName("label_noteNew")
        self.horizontalLayout_2.addWidget(self.label_noteNew)
        self.textEdit_noteNew = QtWidgets.QTextEdit(self.widget_puNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_noteNew.sizePolicy().hasHeightForWidth())
        self.textEdit_noteNew.setSizePolicy(sizePolicy)
        self.textEdit_noteNew.setMinimumSize(QtCore.QSize(130, 20))
        self.textEdit_noteNew.setMaximumSize(QtCore.QSize(0, 40))
        self.textEdit_noteNew.setObjectName("textEdit_noteNew")
        self.horizontalLayout_2.addWidget(self.textEdit_noteNew)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.checkBoxNew = QtWidgets.QCheckBox(self.widget_puNew)
        self.checkBoxNew.setEnabled(True)
        self.checkBoxNew.setMinimumSize(QtCore.QSize(0, 20))
        self.checkBoxNew.setCheckable(True)
        self.checkBoxNew.setChecked(True)
        self.checkBoxNew.setObjectName("checkBoxNew")
        self.horizontalLayout_2.addWidget(self.checkBoxNew)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_dateNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_dateNew.setObjectName("label_dateNew")
        self.verticalLayout_11.addWidget(self.label_dateNew)
        self.dateTimeEdit_dateNew = QtWidgets.QDateTimeEdit(self.widget_puNew)
        self.dateTimeEdit_dateNew.setObjectName("dateTimeEdit_dateNew")
        self.verticalLayout_11.addWidget(self.dateTimeEdit_dateNew)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_valNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_valNew.setObjectName("label_valNew")
        self.verticalLayout_12.addWidget(self.label_valNew)
        self.lineEdit_valNew = QtWidgets.QLineEdit(self.widget_puNew)
        self.lineEdit_valNew.setObjectName("lineEdit_valNew")
        self.verticalLayout_12.addWidget(self.lineEdit_valNew)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_impNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_impNew.setObjectName("label_impNew")
        self.verticalLayout_13.addWidget(self.label_impNew)
        self.lineEdit_impNew = QtWidgets.QLineEdit(self.widget_puNew)
        self.lineEdit_impNew.setObjectName("lineEdit_impNew")
        self.verticalLayout_13.addWidget(self.lineEdit_impNew)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.label_errorNew = QtWidgets.QLabel(self.widget_puNew)
        self.label_errorNew.setText("")
        self.label_errorNew.setObjectName("label_errorNew")
        self.horizontalLayout_15.addWidget(self.label_errorNew)
        self.pushButton_replaceNew = QtWidgets.QPushButton(self.widget_puNew)
        self.pushButton_replaceNew.setObjectName("pushButton_replaceNew")
        self.horizontalLayout_15.addWidget(self.pushButton_replaceNew)
        self.pushButton_canselNew = QtWidgets.QPushButton(self.widget_puNew)
        self.pushButton_canselNew.setObjectName("pushButton_canselNew")
        self.horizontalLayout_15.addWidget(self.pushButton_canselNew)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout.addWidget(self.widget_puNew)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_serKpu.setText(_translate("Form", "S/N КПУ"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_flat.setText(_translate("Form", "Квартира"))
        self.label_klemma.setText(_translate("Form", "Клемма"))
        self.label_serial.setText(_translate("Form", "Сер.Ном"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.label_coef.setText(_translate("Form", "Коэффициент"))
        self.label_marka.setText(_translate("Form", "Марка"))
        self.comboBox_type.setItemText(1, _translate("Form", "ГВС"))
        self.comboBox_type.setItemText(2, _translate("Form", "ХВС"))
        self.comboBox_type.setItemText(3, _translate("Form", "Т"))
        self.comboBox_type.setItemText(4, _translate("Form", "Э"))
        self.label_4.setText(_translate("Form", "Этаж"))
        self.label_floor.setText(_translate("Form", "TextLabel"))
        self.label_35.setText(_translate("Form", "показания"))
        self.label_pokaz.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "дата посл.показаний"))
        self.label_dateLast.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "дата подключения"))
        self.label_dateOn.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "дата отключения"))
        self.label_dateOff.setText(_translate("Form", "TextLabel"))
        self.label_entr.setText(_translate("Form", "TextLabel"))
        self.label_1.setText(_translate("Form", "Подъезд"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.pushButton_kpu.setText(_translate("Form", "КПУ"))
        self.pushButton_replace.setText(_translate("Form", "Замена"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("Form", "Информация"))
        item = self.tableWidget_stZn.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Дата"))
        item = self.tableWidget_stZn.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Показания"))
        item = self.tableWidget_stZn.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Импульсы"))
        self.label_date.setText(_translate("Form", "Дата"))
        self.label_pok.setText(_translate("Form", "Показания"))
        self.label_imp.setText(_translate("Form", "Импульсы"))
        self.pushButton_addStart.setText(_translate("Form", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_startZn), _translate("Form", "Стартовые значения"))
        self.pushButton_showVal.setText(_translate("Form", "Показать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_value), _translate("Form", "Показания"))
        item = self.tableWidget_history.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Город"))
        item = self.tableWidget_history.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Улица"))
        item = self.tableWidget_history.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Дом"))
        item = self.tableWidget_history.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Квартира"))
        item = self.tableWidget_history.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Клемма"))
        item = self.tableWidget_history.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Работоспособность"))
        item = self.tableWidget_history.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Дата редактирования"))
        item = self.tableWidget_history.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Дата отключения"))
        item = self.tableWidget_history.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Примечания"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), _translate("Form", "История редактирования"))
        self.label_serialNew.setText(_translate("Form", "сер.ном"))
        self.label_coefNew.setText(_translate("Form", "коэффициент"))
        self.label_markaNew.setText(_translate("Form", "Марка"))
        self.label_klemmaNew.setText(_translate("Form", "клемма"))
        self.label_noteNew.setText(_translate("Form", "Примечания"))
        self.checkBoxNew.setText(_translate("Form", "работоспособность"))
        self.label_dateNew.setText(_translate("Form", "Дата"))
        self.label_valNew.setText(_translate("Form", "Показания"))
        self.label_impNew.setText(_translate("Form", "Импульсы"))
        self.pushButton_replaceNew.setText(_translate("Form", "Заменить"))
        self.pushButton_canselNew.setText(_translate("Form", "Отмена"))
