# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KPU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1106, 812)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_city = QtWidgets.QLabel(Form)
        self.label_city.setObjectName("label_city")
        self.horizontalLayout.addWidget(self.label_city)
        self.comboBox_city = QtWidgets.QComboBox(Form)
        self.comboBox_city.setObjectName("comboBox_city")
        self.comboBox_city.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_city)
        self.label_street = QtWidgets.QLabel(Form)
        self.label_street.setObjectName("label_street")
        self.horizontalLayout.addWidget(self.label_street)
        self.comboBox_street = QtWidgets.QComboBox(Form)
        self.comboBox_street.setObjectName("comboBox_street")
        self.horizontalLayout.addWidget(self.comboBox_street)
        self.label_house = QtWidgets.QLabel(Form)
        self.label_house.setObjectName("label_house")
        self.horizontalLayout.addWidget(self.label_house)
        self.comboBox_house = QtWidgets.QComboBox(Form)
        self.comboBox_house.setObjectName("comboBox_house")
        self.horizontalLayout.addWidget(self.comboBox_house)
        self.label_entrance = QtWidgets.QLabel(Form)
        self.label_entrance.setObjectName("label_entrance")
        self.horizontalLayout.addWidget(self.label_entrance)
        self.comboBox_entrance = QtWidgets.QComboBox(Form)
        self.comboBox_entrance.setObjectName("comboBox_entrance")
        self.horizontalLayout.addWidget(self.comboBox_entrance)
        self.pushButton_filtr = QtWidgets.QPushButton(Form)
        self.pushButton_filtr.setObjectName("pushButton_filtr")
        self.horizontalLayout.addWidget(self.pushButton_filtr)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_kpu = QtWidgets.QTableWidget(Form)
        self.tableWidget_kpu.setEnabled(True)
        self.tableWidget_kpu.setMouseTracking(True)
        self.tableWidget_kpu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_kpu.setAcceptDrops(False)
        self.tableWidget_kpu.setToolTip("")
        self.tableWidget_kpu.setStatusTip("")
        self.tableWidget_kpu.setAutoFillBackground(False)
        self.tableWidget_kpu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_kpu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_kpu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_kpu.setTabKeyNavigation(True)
        self.tableWidget_kpu.setProperty("showDropIndicator", True)
        self.tableWidget_kpu.setDragEnabled(False)
        self.tableWidget_kpu.setDragDropOverwriteMode(True)
        self.tableWidget_kpu.setAlternatingRowColors(False)
        self.tableWidget_kpu.setShowGrid(True)
        self.tableWidget_kpu.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_kpu.setWordWrap(True)
        self.tableWidget_kpu.setCornerButtonEnabled(True)
        self.tableWidget_kpu.setObjectName("tableWidget_kpu")
        self.tableWidget_kpu.setColumnCount(10)
        self.tableWidget_kpu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_kpu.setHorizontalHeaderItem(9, item)
        self.tableWidget_kpu.horizontalHeader().setVisible(True)
        self.tableWidget_kpu.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_kpu.horizontalHeader().setDefaultSectionSize(149)
        self.verticalLayout.addWidget(self.tableWidget_kpu)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.comboBox_city.setItemText(0, _translate("Form", "Обнинск"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.pushButton_filtr.setText(_translate("Form", "Отфильтровать"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.tableWidget_kpu.setSortingEnabled(False)
        item = self.tableWidget_kpu.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Город"))
        item = self.tableWidget_kpu.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Улица"))
        item = self.tableWidget_kpu.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Дом"))
        item = self.tableWidget_kpu.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Подъезд"))
        item = self.tableWidget_kpu.horizontalHeaderItem(4)
        item.setText(_translate("Form", "S/N"))
        item = self.tableWidget_kpu.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Адрес"))
        item = self.tableWidget_kpu.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Тип"))
        item = self.tableWidget_kpu.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Этаж"))
        item = self.tableWidget_kpu.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Примечания"))
        item = self.tableWidget_kpu.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Работоспособность"))
