# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(720, 480)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_replacePU = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_replacePU.setObjectName("tableWidget_replacePU")
        self.tableWidget_replacePU.setColumnCount(3)
        self.tableWidget_replacePU.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replacePU.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replacePU.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replacePU.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_replacePU, 1, 1, 1, 1)
        self.label_replaceKPU = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_replaceKPU.sizePolicy().hasHeightForWidth())
        self.label_replaceKPU.setSizePolicy(sizePolicy)
        self.label_replaceKPU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_replaceKPU.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_replaceKPU.setTextFormat(QtCore.Qt.AutoText)
        self.label_replaceKPU.setAlignment(QtCore.Qt.AlignCenter)
        self.label_replaceKPU.setObjectName("label_replaceKPU")
        self.gridLayout.addWidget(self.label_replaceKPU, 0, 0, 1, 1)
        self.label_replacePU = QtWidgets.QLabel(self.centralwidget)
        self.label_replacePU.setAlignment(QtCore.Qt.AlignCenter)
        self.label_replacePU.setObjectName("label_replacePU")
        self.gridLayout.addWidget(self.label_replacePU, 0, 1, 1, 1)
        self.tableWidget_replaceKPU = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_replaceKPU.setObjectName("tableWidget_replaceKPU")
        self.tableWidget_replaceKPU.setColumnCount(3)
        self.tableWidget_replaceKPU.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replaceKPU.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replaceKPU.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_replaceKPU.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_replaceKPU, 1, 0, 1, 1)
        self.tableWidget_lineState = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_lineState.setObjectName("tableWidget_lineState")
        self.tableWidget_lineState.setColumnCount(16)
        self.tableWidget_lineState.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lineState.setHorizontalHeaderItem(15, item)
        self.gridLayout.addWidget(self.tableWidget_lineState, 1, 2, 1, 1)
        self.label_lineState = QtWidgets.QLabel(self.centralwidget)
        self.label_lineState.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lineState.setObjectName("label_lineState")
        self.gridLayout.addWidget(self.label_lineState, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_analysis = QtWidgets.QMenu(self.menubar)
        self.menu_analysis.setObjectName("menu_analysis")
        MainWindow.setMenuBar(self.menubar)
        self.action_scaut = QtWidgets.QAction(MainWindow)
        self.action_scaut.setObjectName("action_scaut")
        self.action_kpu = QtWidgets.QAction(MainWindow)
        self.action_kpu.setObjectName("action_kpu")
        self.action_pu = QtWidgets.QAction(MainWindow)
        self.action_pu.setObjectName("action_pu")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_lineState = QtWidgets.QAction(MainWindow)
        self.action_lineState.setObjectName("action_lineState")
        self.menu.addAction(self.action_scaut)
        self.menu.addAction(self.action_kpu)
        self.menu.addAction(self.action_pu)
        self.menu.addAction(self.action_quit)
        self.menu_analysis.addSeparator()
        self.menu_analysis.addAction(self.action_lineState)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_analysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_replacePU.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Старый сер.ном"))
        item = self.tableWidget_replacePU.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новый сер.ном"))
        item = self.tableWidget_replacePU.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата замены"))
        self.label_replaceKPU.setText(_translate("MainWindow", "История замены КПУ"))
        self.label_replacePU.setText(_translate("MainWindow", "История замены ПУ"))
        item = self.tableWidget_replaceKPU.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Старый сер.ном"))
        item = self.tableWidget_replaceKPU.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новый сер.ном"))
        item = self.tableWidget_replaceKPU.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дата замены"))
        item = self.tableWidget_lineState.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Город"))
        item = self.tableWidget_lineState.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Улица"))
        item = self.tableWidget_lineState.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Дом"))
        item = self.tableWidget_lineState.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Подъезд"))
        item = self.tableWidget_lineState.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Этаж"))
        item = self.tableWidget_lineState.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "№Кв."))
        item = self.tableWidget_lineState.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "S/N КПУ"))
        item = self.tableWidget_lineState.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Клемма"))
        item = self.tableWidget_lineState.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "S/N ПУ"))
        item = self.tableWidget_lineState.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Тип"))
        item = self.tableWidget_lineState.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Марка"))
        item = self.tableWidget_lineState.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Показания"))
        item = self.tableWidget_lineState.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Импульсы"))
        item = self.tableWidget_lineState.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "line state"))
        item = self.tableWidget_lineState.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "empty"))
        item = self.tableWidget_lineState.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Последняя дата"))
        self.label_lineState.setText(_translate("MainWindow", "Контроль линии"))
        self.menu.setTitle(_translate("MainWindow", "Оборудование"))
        self.menu_analysis.setTitle(_translate("MainWindow", "Анализ данных"))
        self.action_scaut.setText(_translate("MainWindow", "СКАУТ"))
        self.action_kpu.setText(_translate("MainWindow", "КПУ"))
        self.action_pu.setText(_translate("MainWindow", "ПУ"))
        self.action_quit.setText(_translate("MainWindow", "Выход"))
        self.action_lineState.setText(_translate("MainWindow", "Контроль линии"))
