# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1086, 715)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_city = QtWidgets.QLabel(Form)
        self.label_city.setObjectName("label_city")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.comboBox_city = QtWidgets.QComboBox(Form)
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.label_type = QtWidgets.QLabel(Form)
        self.label_type.setObjectName("label_type")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(Form)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.setItemText(0, "")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_street = QtWidgets.QLabel(Form)
        self.label_street.setObjectName("label_street")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.comboBox_street = QtWidgets.QComboBox(Form)
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.label_snKpu = QtWidgets.QLabel(Form)
        self.label_snKpu.setObjectName("label_snKpu")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_snKpu)
        self.comboBox_serKpu = QtWidgets.QComboBox(Form)
        self.comboBox_serKpu.setObjectName("comboBox_serKpu")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_serKpu)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_house = QtWidgets.QLabel(Form)
        self.label_house.setObjectName("label_house")
        self.horizontalLayout_2.addWidget(self.label_house)
        self.comboBox_house = QtWidgets.QComboBox(Form)
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.horizontalLayout_2.addWidget(self.comboBox_house)
        self.label_entr = QtWidgets.QLabel(Form)
        self.label_entr.setObjectName("label_entr")
        self.horizontalLayout_2.addWidget(self.label_entr)
        self.comboBox_entr = QtWidgets.QComboBox(Form)
        self.comboBox_entr.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_entr.setObjectName("comboBox_entr")
        self.horizontalLayout_2.addWidget(self.comboBox_entr)
        self.label_floor = QtWidgets.QLabel(Form)
        self.label_floor.setObjectName("label_floor")
        self.horizontalLayout_2.addWidget(self.label_floor)
        self.comboBox_floor = QtWidgets.QComboBox(Form)
        self.comboBox_floor.setObjectName("comboBox_floor")
        self.horizontalLayout_2.addWidget(self.comboBox_floor)
        self.label_flat = QtWidgets.QLabel(Form)
        self.label_flat.setObjectName("label_flat")
        self.horizontalLayout_2.addWidget(self.label_flat)
        self.comboBox_flat = QtWidgets.QComboBox(Form)
        self.comboBox_flat.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_flat.setObjectName("comboBox_flat")
        self.horizontalLayout_2.addWidget(self.comboBox_flat)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_filtr = QtWidgets.QPushButton(Form)
        self.pushButton_filtr.setObjectName("pushButton_filtr")
        self.horizontalLayout_2.addWidget(self.pushButton_filtr)
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_2.addWidget(self.pushButton_add)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_pu = QtWidgets.QTableWidget(Form)
        self.tableWidget_pu.setMouseTracking(True)
        self.tableWidget_pu.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_pu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pu.setObjectName("tableWidget_pu")
        self.tableWidget_pu.setColumnCount(17)
        self.tableWidget_pu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(16, item)
        self.tableWidget_pu.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout.addWidget(self.tableWidget_pu)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_type.setText(_translate("Form", "Тип ПУ"))
        self.comboBox_type.setItemText(1, _translate("Form", "ГВС"))
        self.comboBox_type.setItemText(2, _translate("Form", "ХВС"))
        self.comboBox_type.setItemText(3, _translate("Form", "Т"))
        self.comboBox_type.setItemText(4, _translate("Form", "Э"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_snKpu.setText(_translate("Form", "S/N КПУ"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entr.setText(_translate("Form", "Подъезд"))
        self.label_floor.setText(_translate("Form", "Этаж"))
        self.label_flat.setText(_translate("Form", "Квартира"))
        self.pushButton_filtr.setText(_translate("Form", "Обновить"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.checkBox.setText(_translate("Form", "активные"))
        self.tableWidget_pu.setSortingEnabled(True)
        item = self.tableWidget_pu.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id_klemma"))
        item = self.tableWidget_pu.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Город"))
        item = self.tableWidget_pu.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Улица"))
        item = self.tableWidget_pu.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Дом"))
        item = self.tableWidget_pu.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Подъезд"))
        item = self.tableWidget_pu.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Этаж"))
        item = self.tableWidget_pu.horizontalHeaderItem(6)
        item.setText(_translate("Form", "№ Кв."))
        item = self.tableWidget_pu.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Тип ПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Сер.Ном.ПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(9)
        item.setText(_translate("Form", "S/N КПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Клемма"))
        item = self.tableWidget_pu.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Марка"))
        item = self.tableWidget_pu.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Коэффициент"))
        item = self.tableWidget_pu.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Показания"))
        item = self.tableWidget_pu.horizontalHeaderItem(14)
        item.setText(_translate("Form", "Дата подключения"))
        item = self.tableWidget_pu.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Дата отключения"))
        item = self.tableWidget_pu.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Работоспособность"))
