# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_city = QtWidgets.QLabel(Form)
        self.label_city.setObjectName("label_city")
        self.horizontalLayout.addWidget(self.label_city)
        self.comboBox_city = QtWidgets.QComboBox(Form)
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.horizontalLayout.addWidget(self.comboBox_city)
        self.label_street = QtWidgets.QLabel(Form)
        self.label_street.setObjectName("label_street")
        self.horizontalLayout.addWidget(self.label_street)
        self.comboBox_street = QtWidgets.QComboBox(Form)
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.horizontalLayout.addWidget(self.comboBox_street)
        self.label_house = QtWidgets.QLabel(Form)
        self.label_house.setObjectName("label_house")
        self.horizontalLayout.addWidget(self.label_house)
        self.comboBox_house = QtWidgets.QComboBox(Form)
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.horizontalLayout.addWidget(self.comboBox_house)
        self.label_entrance = QtWidgets.QLabel(Form)
        self.label_entrance.setObjectName("label_entrance")
        self.horizontalLayout.addWidget(self.label_entrance)
        self.comboBox_entrance = QtWidgets.QComboBox(Form)
        self.comboBox_entrance.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_entrance.setObjectName("comboBox_entrance")
        self.horizontalLayout.addWidget(self.comboBox_entrance)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.pushButton_filtr = QtWidgets.QPushButton(Form)
        self.pushButton_filtr.setObjectName("pushButton_filtr")
        self.horizontalLayout.addWidget(self.pushButton_filtr)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_pu = QtWidgets.QTableWidget(Form)
        self.tableWidget_pu.setMouseTracking(True)
        self.tableWidget_pu.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_pu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pu.setObjectName("tableWidget_pu")
        self.tableWidget_pu.setColumnCount(17)
        self.tableWidget_pu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pu.setHorizontalHeaderItem(16, item)
        self.tableWidget_pu.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout.addWidget(self.tableWidget_pu)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_3.setText(_translate("Form", "Этаж"))
        self.label.setText(_translate("Form", "Квартира"))
        self.label_2.setText(_translate("Form", "Тип"))
        self.checkBox.setText(_translate("Form", "активные"))
        self.pushButton_filtr.setText(_translate("Form", "Обновить"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.tableWidget_pu.setSortingEnabled(True)
        item = self.tableWidget_pu.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id_klemma"))
        item = self.tableWidget_pu.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Город"))
        item = self.tableWidget_pu.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Улица"))
        item = self.tableWidget_pu.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Дом"))
        item = self.tableWidget_pu.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Подъезд"))
        item = self.tableWidget_pu.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Этаж"))
        item = self.tableWidget_pu.horizontalHeaderItem(6)
        item.setText(_translate("Form", "№ Кв."))
        item = self.tableWidget_pu.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Тип ПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Сер.Ном.ПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(9)
        item.setText(_translate("Form", "S/N КПУ"))
        item = self.tableWidget_pu.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Клемма"))
        item = self.tableWidget_pu.horizontalHeaderItem(11)
        item.setText(_translate("Form", "Марка"))
        item = self.tableWidget_pu.horizontalHeaderItem(12)
        item.setText(_translate("Form", "Коэффициент"))
        item = self.tableWidget_pu.horizontalHeaderItem(13)
        item.setText(_translate("Form", "Показания"))
        item = self.tableWidget_pu.horizontalHeaderItem(14)
        item.setText(_translate("Form", "Дата подключения"))
        item = self.tableWidget_pu.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Дата отключения"))
        item = self.tableWidget_pu.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Работоспособность"))
