# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_PU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 344)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 491, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_19)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_20.setEnabled(False)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_20)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_29.setEnabled(False)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_30.setEnabled(False)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_32.setEnabled(False)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_32)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.horizontalLayout_3.addLayout(self.formLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 481, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget_3)
        self.dateTimeEdit.setDate(QtCore.QDate(2020, 2, 13))
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget_3)
        self.dateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 2, 19), QtCore.QTime(9, 0, 0)))
        self.dateTimeEdit_2.setDate(QtCore.QDate(2020, 2, 19))
        self.dateTimeEdit_2.setMinimumDate(QtCore.QDate(2017, 1, 1))
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setCurrentSectionIndex(0)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_8.addWidget(self.dateTimeEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableView_3 = QtWidgets.QTableView(self.verticalLayoutWidget_3)
        self.tableView_3.setObjectName("tableView_3")
        self.horizontalLayout_9.addWidget(self.tableView_3)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.verticalLayoutWidget_3)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_9.addWidget(self.verticalScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(500, 40, 20, 291))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(520, 40, 461, 291))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_21)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_24.setEnabled(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_24)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(12)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.horizontalLayout_10.addLayout(self.formLayout_7)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_33)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_34)
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_36)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.horizontalLayout_10.addLayout(self.formLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_11.addWidget(self.checkBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_19.addWidget(self.label_25)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_18.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_18.addWidget(self.lineEdit_16)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_18.addWidget(self.lineEdit_25)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_12.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_12.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_17.setText(_translate("Form", "№ Кв."))
        self.label_18.setText(_translate("Form", "S/N КПУ"))
        self.label_19.setText(_translate("Form", "Клемма"))
        self.label_20.setText(_translate("Form", "Сер.Ном"))
        self.label_2.setText(_translate("Form", "Тип"))
        self.label_3.setText(_translate("Form", "Модель"))
        self.label_29.setText(_translate("Form", "коэффициент"))
        self.label_30.setText(_translate("Form", "показания"))
        self.label_32.setText(_translate("Form", "дата подключения"))
        self.label.setText(_translate("Form", "дата отключения"))
        self.label_4.setText(_translate("Form", "Примечания"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.label_9.setText(_translate("Form", "iid_klemma = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Информация"))
        self.pushButton_2.setText(_translate("Form", "Показать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Показания"))
        self.label_21.setText(_translate("Form", "№ Кв."))
        self.label_23.setText(_translate("Form", "Клемма"))
        self.label_24.setText(_translate("Form", "Сер.Ном"))
        self.label_8.setText(_translate("Form", "Тип"))
        self.label_33.setText(_translate("Form", "Модель"))
        self.label_34.setText(_translate("Form", "коэффициент"))
        self.label_36.setText(_translate("Form", "дата подключения"))
        self.label_11.setText(_translate("Form", "Примечания"))
        self.checkBox_2.setText(_translate("Form", "работоспособность"))
        self.label_5.setText(_translate("Form", "Стартовое значение:"))
        self.label_15.setText(_translate("Form", "Дата"))
        self.label_16.setText(_translate("Form", "Показания"))
        self.label_25.setText(_translate("Form", "Импульсы"))
        self.pushButton_5.setText(_translate("Form", "Замена"))
        self.pushButton_6.setText(_translate("Form", "Сохранить"))
