# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_KPU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(772, 269)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_city = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_city.setObjectName("label_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.lineEdit_city = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_city.setEnabled(False)
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_city)
        self.label_street = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_street.setObjectName("label_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.lineEdit_street = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_street.setEnabled(False)
        self.lineEdit_street.setObjectName("lineEdit_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_street)
        self.label_house = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_house.setObjectName("label_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.lineEdit_house = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_house.setEnabled(False)
        self.lineEdit_house.setObjectName("lineEdit_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_house)
        self.label_entrance = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_entrance.setObjectName("label_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entrance)
        self.lineEdit_entrance = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_entrance.setEnabled(False)
        self.lineEdit_entrance.setObjectName("lineEdit_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_entrance)
        self.label_floor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_floor.setObjectName("label_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_floor)
        self.lineEdit_floor = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_floor.setEnabled(False)
        self.lineEdit_floor.setObjectName("lineEdit_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_floor)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_serial = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_serial.setEnabled(False)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_adress = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_adress.setObjectName("label_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adress)
        self.lineEdit_adress = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_adress.setEnabled(False)
        self.lineEdit_adress.setObjectName("lineEdit_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_adress)
        self.label_type = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_type.setObjectName("label_type")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.lineEdit_type = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_type.setEnabled(False)
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_type)
        self.label_note = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_note.setObjectName("label_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_note)
        self.lineEdit_note = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_note.setEnabled(False)
        self.lineEdit_note.setObjectName("lineEdit_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_note)
        self.horizontalLayout_3.addLayout(self.formLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(470, 10, 31, 251))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 10, 261, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_serialNew = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_serialNew.setObjectName("label_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serialNew)
        self.lineEdit_serialNew = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_serialNew.setObjectName("lineEdit_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serialNew)
        self.label_adressNew = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_adressNew.setObjectName("label_adressNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adressNew)
        self.lineEdit_adressNew = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_adressNew.setObjectName("lineEdit_adressNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_adressNew)
        self.label_typeNew = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_typeNew.setObjectName("label_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_typeNew)
        self.lineEdit_typeNew = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_typeNew.setObjectName("lineEdit_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_typeNew)
        self.label_noteNew = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_noteNew.setObjectName("label_noteNew")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_noteNew)
        self.lineEdit_noteNew = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_noteNew.setObjectName("lineEdit_noteNew")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_noteNew)
        self.horizontalLayout_4.addLayout(self.formLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.checkBoxNew = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxNew.setEnabled(True)
        self.checkBoxNew.setCheckable(True)
        self.checkBoxNew.setChecked(True)
        self.checkBoxNew.setObjectName("checkBoxNew")
        self.horizontalLayout_5.addWidget(self.checkBoxNew)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_replace = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout_6.addWidget(self.pushButton_replace)
        self.pushButton_cansel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_cansel.setObjectName("pushButton_cansel")
        self.horizontalLayout_6.addWidget(self.pushButton_cansel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_floor.setText(_translate("Form", "Этаж"))
        self.label_serial.setText(_translate("Form", "сер.ном"))
        self.label_adress.setText(_translate("Form", "Адрес"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.label_note.setText(_translate("Form", "Примечания"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.label_serialNew.setText(_translate("Form", "сер.ном"))
        self.label_adressNew.setText(_translate("Form", "Адрес"))
        self.label_typeNew.setText(_translate("Form", "Тип"))
        self.label_noteNew.setText(_translate("Form", "Примечания"))
        self.checkBoxNew.setText(_translate("Form", "работоспособность"))
        self.pushButton_replace.setText(_translate("Form", "Заменить"))
        self.pushButton_cansel.setText(_translate("Form", "Отмена"))
