# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_KPU.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(921, 269)
        Form.setMinimumSize(QtCore.QSize(479, 269))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_kpu = QtWidgets.QFrame(Form)
        self.frame_kpu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kpu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kpu.setObjectName("frame_kpu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_kpu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_city = QtWidgets.QLabel(self.frame_kpu)
        self.label_city.setObjectName("label_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_city)
        self.label_street = QtWidgets.QLabel(self.frame_kpu)
        self.label_street.setObjectName("label_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_street)
        self.label_house = QtWidgets.QLabel(self.frame_kpu)
        self.label_house.setObjectName("label_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_house)
        self.label_entrance = QtWidgets.QLabel(self.frame_kpu)
        self.label_entrance.setObjectName("label_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_entrance)
        self.label_floor = QtWidgets.QLabel(self.frame_kpu)
        self.label_floor.setObjectName("label_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_floor)
        self.lineEdit_floor = QtWidgets.QLineEdit(self.frame_kpu)
        self.lineEdit_floor.setEnabled(True)
        self.lineEdit_floor.setObjectName("lineEdit_floor")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_floor)
        self.comboBox_city = QtWidgets.QComboBox(self.frame_kpu)
        self.comboBox_city.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_city.setObjectName("comboBox_city")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_city)
        self.comboBox_street = QtWidgets.QComboBox(self.frame_kpu)
        self.comboBox_street.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_street.setObjectName("comboBox_street")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_street)
        self.comboBox_house = QtWidgets.QComboBox(self.frame_kpu)
        self.comboBox_house.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_house.setObjectName("comboBox_house")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_house)
        self.comboBox_entrance = QtWidgets.QComboBox(self.frame_kpu)
        self.comboBox_entrance.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_entrance.setObjectName("comboBox_entrance")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_entrance)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_serial = QtWidgets.QLabel(self.frame_kpu)
        self.label_serial.setObjectName("label_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serial)
        self.lineEdit_serial = QtWidgets.QLineEdit(self.frame_kpu)
        self.lineEdit_serial.setEnabled(True)
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serial)
        self.label_adress = QtWidgets.QLabel(self.frame_kpu)
        self.label_adress.setObjectName("label_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adress)
        self.label_type = QtWidgets.QLabel(self.frame_kpu)
        self.label_type.setObjectName("label_type")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.label_note = QtWidgets.QLabel(self.frame_kpu)
        self.label_note.setObjectName("label_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_note)
        self.lineEdit_note = QtWidgets.QLineEdit(self.frame_kpu)
        self.lineEdit_note.setEnabled(True)
        self.lineEdit_note.setObjectName("lineEdit_note")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_note)
        self.spinBox_adress = QtWidgets.QSpinBox(self.frame_kpu)
        self.spinBox_adress.setSizeIncrement(QtCore.QSize(0, 0))
        self.spinBox_adress.setMinimum(1)
        self.spinBox_adress.setMaximum(255)
        self.spinBox_adress.setProperty("value", 255)
        self.spinBox_adress.setObjectName("spinBox_adress")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_adress)
        self.comboBox_type = QtWidgets.QComboBox(self.frame_kpu)
        self.comboBox_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_type.setObjectName("comboBox_type")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_type)
        self.horizontalLayout_3.addLayout(self.formLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.frame_kpu)
        self.checkBox.setEnabled(True)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.pushButton_pu = QtWidgets.QPushButton(self.frame_kpu)
        self.pushButton_pu.setObjectName("pushButton_pu")
        self.horizontalLayout_8.addWidget(self.pushButton_pu)
        self.pushButton_replace = QtWidgets.QPushButton(self.frame_kpu)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout_8.addWidget(self.pushButton_replace)
        self.pushButton_save = QtWidgets.QPushButton(self.frame_kpu)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_8.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_kpu)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_kpuNew = QtWidgets.QFrame(Form)
        self.frame_kpuNew.setEnabled(True)
        self.frame_kpuNew.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_kpuNew.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kpuNew.setObjectName("frame_kpuNew")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_kpuNew)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_serialNew = QtWidgets.QLabel(self.frame_kpuNew)
        self.label_serialNew.setObjectName("label_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_serialNew)
        self.lineEdit_serialNew = QtWidgets.QLineEdit(self.frame_kpuNew)
        self.lineEdit_serialNew.setObjectName("lineEdit_serialNew")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_serialNew)
        self.label_adressNew = QtWidgets.QLabel(self.frame_kpuNew)
        self.label_adressNew.setObjectName("label_adressNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adressNew)
        self.label_typeNew = QtWidgets.QLabel(self.frame_kpuNew)
        self.label_typeNew.setObjectName("label_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_typeNew)
        self.label_noteNew = QtWidgets.QLabel(self.frame_kpuNew)
        self.label_noteNew.setObjectName("label_noteNew")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_noteNew)
        self.lineEdit_noteNew = QtWidgets.QLineEdit(self.frame_kpuNew)
        self.lineEdit_noteNew.setObjectName("lineEdit_noteNew")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_noteNew)
        self.spinBox_adressNew = QtWidgets.QSpinBox(self.frame_kpuNew)
        self.spinBox_adressNew.setMinimum(1)
        self.spinBox_adressNew.setMaximum(255)
        self.spinBox_adressNew.setSingleStep(1)
        self.spinBox_adressNew.setProperty("value", 255)
        self.spinBox_adressNew.setObjectName("spinBox_adressNew")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_adressNew)
        self.comboBox_typeNew = QtWidgets.QComboBox(self.frame_kpuNew)
        self.comboBox_typeNew.setObjectName("comboBox_typeNew")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_typeNew)
        self.horizontalLayout_4.addLayout(self.formLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.checkBoxNew = QtWidgets.QCheckBox(self.frame_kpuNew)
        self.checkBoxNew.setEnabled(True)
        self.checkBoxNew.setCheckable(True)
        self.checkBoxNew.setChecked(True)
        self.checkBoxNew.setObjectName("checkBoxNew")
        self.horizontalLayout_5.addWidget(self.checkBoxNew)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_replaceNew = QtWidgets.QPushButton(self.frame_kpuNew)
        self.pushButton_replaceNew.setObjectName("pushButton_replaceNew")
        self.horizontalLayout_6.addWidget(self.pushButton_replaceNew)
        self.pushButton_canselNew = QtWidgets.QPushButton(self.frame_kpuNew)
        self.pushButton_canselNew.setObjectName("pushButton_canselNew")
        self.horizontalLayout_6.addWidget(self.pushButton_canselNew)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_kpuNew)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_city.setText(_translate("Form", "Город"))
        self.label_street.setText(_translate("Form", "Улица"))
        self.label_house.setText(_translate("Form", "Дом"))
        self.label_entrance.setText(_translate("Form", "Подъезд"))
        self.label_floor.setText(_translate("Form", "Этаж"))
        self.label_serial.setText(_translate("Form", "сер.ном"))
        self.label_adress.setText(_translate("Form", "Адрес"))
        self.label_type.setText(_translate("Form", "Тип"))
        self.label_note.setText(_translate("Form", "Примечания"))
        self.checkBox.setText(_translate("Form", "работоспособность"))
        self.pushButton_pu.setText(_translate("Form", "ПУ"))
        self.pushButton_replace.setText(_translate("Form", "Замена"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.label_serialNew.setText(_translate("Form", "сер.ном"))
        self.label_adressNew.setText(_translate("Form", "Адрес"))
        self.label_typeNew.setText(_translate("Form", "Тип"))
        self.label_noteNew.setText(_translate("Form", "Примечания"))
        self.checkBoxNew.setText(_translate("Form", "работоспособность"))
        self.pushButton_replaceNew.setText(_translate("Form", "Заменить"))
        self.pushButton_canselNew.setText(_translate("Form", "Отмена"))
